# Site settings
title: "Lizuo Liu's Homepage"
description: "A resume of Lizuo Liu."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Lizuo Liu"
resume_title:                   "Learner, Researcher"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "lizuol@smu.edu"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "682-331-1601"
resume_contact_address:         ""

resume_header_contact_info:     "5600 SMU Blvd• 682-331-1601 • lizuol@smu.edu"
display_header_contact_info:    "false"

resume_header_intro: "<p>不积跬步，无以至千里；不积小流，无以成江海。A journey of one thousand miles can never be made without the accumulation of every single step;An ocean can never be vast without the contribution of every single stream and brook.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_ResearchInterests:      true
resume_section_education:       true
resume_section_Publications:        false
resume_section_Honors:          true
resume_section_teaching:     true
resume_section_ConferenceOrganizations:           true
resume_section_Presentations:    true
resume_section_ProgrammingLanguage:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/leelizuoliu"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
